import type { SkillDocument } from "./types";

const skill = (id: string, name: string, description: string, body: string): SkillDocument => ({
  id, name, description, body, userInvocable: true, source: "builtin",
});

export const BUILTIN_SKILLS: readonly SkillDocument[] = [
  skill("deep-research", "Deep research", "Investigate a question broadly, verify claims, compare sources, and synthesize an evidence-based answer.", `# Deep research\n\nUse when the user asks for a comprehensive investigation rather than a quick lookup.\n\n## Workflow\n1. Restate the research question internally as concrete subquestions. Do not burden the user with a plan unless useful.\n2. Search broadly enough to identify the main actors, terminology, primary sources, and contested points.\n3. Prefer primary/official sources for factual claims; use secondary sources for interpretation and discovery.\n4. Check dates and version relevance. Treat stale documents as historical evidence, not current truth.\n5. Triangulate important claims. If reputable sources disagree, surface the disagreement instead of forcing consensus.\n6. Follow promising references when the first search is insufficient. Do not stop at a thin first page of results.\n7. Separate evidence from inference. Mark uncertainty precisely.\n8. Synthesize around the user's decision/question, not around the order sources were found.\n9. End with the practical implications or unresolved questions when relevant.\n\n## Context economy\nRead only the portions needed. For long PDFs, search first and read targeted pages. Avoid dumping source text into context.`),

  skill("literature-review", "Literature review", "Survey academic literature, identify research traditions, methods, gaps, and representative papers.", `# Literature review\n\n## Workflow\n1. Define the phenomenon, population/domain, and neighboring terminology. Generate synonyms before searching.\n2. Search across multiple phrasings and, when possible, both seminal and recent literature.\n3. Prefer peer-reviewed papers, major reviews/meta-analyses, and authoritative working papers/preprints when the field moves quickly.\n4. Build conceptual clusters rather than a flat bibliography: theories, mechanisms, methods, findings, contradictions.\n5. For each central paper capture: question, sample/data, design, main result, limitation, and why it matters.\n6. Distinguish absence of evidence from evidence of absence.\n7. Identify gaps only after checking adjacent terminology; do not call something unexplored because one phrase is rare.\n8. Produce a concise map of the field plus a short set of high-value papers to read next.\n\nWhen papers are in the vault, use pdf_search then targeted pdf_read.`),

  skill("pdf-analysis", "PDF analysis", "Analyze long PDFs efficiently using local search and targeted page reads.", `# PDF analysis\n\nNever begin by reading an entire long PDF.\n\n## Workflow\n1. Use pdf_info to learn page count, metadata, and outline when useful.\n2. Translate the user's question into several likely search terms, including synonyms and section names.\n3. Use pdf_search to locate candidate pages.\n4. Read only the relevant pages plus small neighboring ranges needed for context.\n5. For claims depending on tables/figures that text extraction cannot represent, say what is missing rather than inventing it.\n6. Cross-check conclusions against abstract/introduction/conclusion only when necessary; do not assume the abstract is sufficient.\n7. Cite or mention page numbers in the answer when useful.\n8. If the PDF appears scanned or has no extractable text, report that limitation clearly.`),

  skill("implementation-plan", "Implementation plan", "Turn a feature request into a low-risk implementation sequence with boundaries, invariants, tests, and rollout steps.", `# Implementation plan\n\n## Workflow\n1. Inspect the current implementation before proposing changes. Identify actual integration points and existing local modifications.\n2. State hard constraints and invariants first.\n3. Decompose by dependency direction: pure data/types -> core logic -> adapters -> UI -> persistence/migration.\n4. Prefer vertical slices that can be built and tested independently.\n5. Explicitly name what each branch must not absorb.\n6. Identify risky assumptions and create an early spike/test for them.\n7. Define acceptance tests for desktop and mobile where applicable.\n8. Include migration/rollback if persisted state or external APIs change.\n9. Recommend commit/PR boundaries that a reviewer can understand independently.`),

  skill("debugging", "Debugging", "Diagnose failures systematically using reproduction, evidence, narrowing, and verification.", `# Debugging\n\n## Workflow\n1. Capture the exact symptom/error and the smallest reliable reproduction.\n2. Separate observed facts from hypotheses.\n3. Inspect the code path and runtime/environment differences before changing code.\n4. Form a small set of competing hypotheses; test the cheapest/highest-information one first.\n5. Change one causal variable at a time when possible.\n6. Prefer fixing the violated assumption at the correct abstraction boundary over adding retries or special cases.\n7. Re-run the original reproduction after the fix.\n8. Test at least one neighboring case to guard against regression.\n9. Record the root cause, not just the patch.`),

  skill("verification", "Verification", "Verify that a change or claim is actually correct using targeted checks rather than visual confidence.", `# Verification\n\n## Workflow\n1. Translate the claim into observable acceptance conditions.\n2. Verify the most important failure modes first.\n3. For code: typecheck/build, focused tests, then the original user flow.\n4. For file edits: re-read the affected region/state after writing.\n5. For mobile features: explicitly test iOS/Android-relevant APIs and lifecycle assumptions; desktop success is not sufficient.\n6. For provider payloads: inspect the actual serialized request shape where possible.\n7. Report what was verified, what was not, and why.`),

  skill("document-review", "Document review", "Review a document for argument, structure, clarity, consistency, evidence, and concrete revision opportunities.", `# Document review\n\nRead the relevant document before judging it.\n\nReview in this order:\n1. Purpose/audience: what is the document trying to accomplish?\n2. Argument/logic: are claims supported and ordered coherently?\n3. Structure: does each section/paragraph have a clear job?\n4. Missing assumptions/evidence/counterarguments.\n5. Terminology and internal consistency.\n6. Sentence-level clarity and unnecessary repetition.\n\nPrioritize high-leverage revisions. Quote or point to exact passages rather than giving generic writing advice.`),

  skill("rewrite-edit", "Rewrite and edit", "Rewrite text while preserving intent, facts, terminology, and the user's requested voice/constraints.", `# Rewrite and edit\n\n## Workflow\n1. Identify the intended audience, purpose, and constraints from context; ask only if genuinely unknowable.\n2. Preserve factual content and domain terminology unless the user asks for substantive changes.\n3. Remove redundancy and repair paragraph flow before polishing individual sentences.\n4. Keep one paragraph/section focused on one main job where appropriate.\n5. Avoid introducing claims not supported by the source text.\n6. When editing a vault note, read current text first and make surgical edits when practical.\n7. Re-read the result for accidental omissions, duplicated text, broken Markdown, and tone drift.`),

  skill("vault-organizer", "Vault organizer", "Organize Obsidian notes conservatively using existing structure, links, metadata, and user conventions.", `# Vault organizer\n\n## Workflow\n1. Inspect the existing folder structure, naming conventions, frontmatter, tags, and representative notes before proposing organization.\n2. Prefer the vault's existing concepts over inventing a new taxonomy.\n3. Distinguish navigation problems from storage problems; links/index notes may be better than moving files.\n4. Make reversible, incremental changes. Avoid mass renames without a clear mapping and verification.\n5. Use Obsidian-aware rename operations so links update.\n6. Preserve metadata unless intentionally changing it.\n7. Verify representative links/files after structural changes.`),

  skill("skill-creator", "Skill creator", "Design or improve a reusable Skill with strong triggering metadata, concise workflow, and progressive disclosure.", `# Skill creator\n\nCreate Skills for repeatable procedures, not generic personality instructions.\n\nA good Skill has:\n- a short stable id,\n- a description that tells the model when to use it,\n- a focused body with an executable workflow,\n- optional resources for long reference material,\n- explicit constraints/failure modes when important.\n\nKeep the main SKILL.md concise. Move bulky examples/reference material to resources. Avoid duplicating rules that belong in global custom instructions or the base agent contract.`),

  skill("agentic-task", "Agentic task", "Execute a multi-step task autonomously: inspect, plan internally, act, verify, recover from errors, and finish.", `# Agentic task\n\nUse for multi-step tasks where the user wants an outcome, not a tutorial.\n\n## Loop\n1. Inspect the relevant current state.\n2. Decide the next smallest useful action.\n3. Execute it with available tools.\n4. Observe the result.\n5. If it failed, diagnose and try a materially different corrective action when reasonable.\n6. Continue until the requested outcome is achieved or a real external blocker remains.\n7. Verify the final state.\n8. Report the result concisely, including unresolved blockers or unverified parts.\n\nDo not stop merely because the task has several steps. Do not repeatedly ask for confirmation when the user's intent is already clear.`),
];

export function getBuiltinSkill(id: string): SkillDocument | undefined {
  return BUILTIN_SKILLS.find((item) => item.id === id);
}
